<a href="https://colab.research.google.com/github/levon10/second/blob/main/Lecture_1_Analyst_Program_Student_Copy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 1 - Introduction to Python

**Content**:
- Introduction to variables and data types
- Functions
- Numpy and Matplotlib
- Plotting time-series data
- Moving averages

**Python is a high-level, interpreted scripting language**:
- It is designed to be easy to read and write.
- It is a great language for beginners.
  - Syntax, grammar, is basically like English.
- Many libraries and frameworks are written for Python.
- If you're interested in Machine Learning, AI, Python is a must.

**Jupyter Notebooks**:
- Usually python is coded in ```.py``` files. But we'll be using a Jupyter notebook, ```.ipynb```.
- Jupyter notebooks are better for visualization and learning.
- Google offers a fantastic resource called Colab, that is a notebook that runs in the cloud.
  - So don't worry if your computer is not powerful enough.

**Cells**
- A cell is a block of code or text that runs independently
- You can run a cell by pressing the play button on the left, or by pressing ```Cmd + Enter``` or ```Ctrl + Enter``` for Windows.

### Datatypes

#### Integers, Floats, Strings, Chars and Booleans

In [ ]:
# integers:

# floats:

# chars (characters)

# strings -> string of chars

# Booleans

False

**Use the built-in print function to display the output of the code.**

In [ ]:
print(True)

**Variable Assignment**
- Variables are used to store data
- Variables are given a descriptive name, and then assigned a value using the ```=``` operator.

In [ ]:
my_variable = 10
variable = 5
greeting = 'hi, hows it going'

In [ ]:
a = 3
print(a)

b = 5
print(a + b)

b = a
print(b + a * a)

#### Lists
- Lists are a commonly used data type in Python.
- They are used to store an ordered collection of items, which can be of different types.
- We call them *mutable* data structures, meaning that they can be changed after they are created.

```python
list = [entry1, entry2, entry3]
```

In [ ]:
## defining a list is simple, just use square brackets and separate elements

my_list = [1,2,3,4]

my_google_price = []

my_list_mixed_dt = []

In [ ]:
print(my_list)

#### Indexing Lists
- Indexing = Accessing
- An index is like the location of an entry within a list
- Indexing always starts at 0 in Python i.e. the first element is at index 0
  - Note this is the case with almost all programming languages (Matlab is an exception)

In [ ]:
my_list = [0,1,2,3,4,5]

# print element at index 1

# printing the last element of a list

True
False


#### For Loops and iterating through Lists
- Let's say we have a long list, we don't want to access each element one by one.
- For loops are used to iterate through a list, or any other iterable object.

In [ ]:
## define a list
my_list = [1,2,3,4,5]

# len() ## length built-in operation

In [ ]:
## let's print the elements of a list


In [ ]:
## here's another way to do the same thing


In [ ]:
## now let's say we have 10 lists, and I want to iterate and print each one of their elements?


#### Conditional Statements
- Check whether or not a condition is satisfied

In [ ]:
## use the if and else block for conditional logic
## let's say we want to check to see who is 18 and above:

### Functions
- Functions are a way to encapsulate code that you want to reuse.
- We can input data into a function, and get data out of a function

In [ ]:
## syntax for defining a function
def function_name(the_inputs):

    return

In [ ]:
## let's define a function that reads a list as input, and prints the list's elements
## call the function my_list_reader







In [ ]:
## calling functions:



In [ ]:
## what if we want our function to output a variable
## example, let's take the sum of the elements in a list
## call the function my_summation_list











### Numpy
- Python has many open-source libraries that make coding a lot easier.
- **Numpy!!**
- Libraries like Numpy provide improvements that make coding a lot more efficient and faster
- Useful functions for linear algebra and statistics

In [ ]:
## importing the library:



#### Arrays
- Arrays can be similar to lists; however, indexing is a lot faster in numpy arrays than in lists, since numpy arrays are stored in contiguous blocks of memory.

In [ ]:
# 0 D array -> scalar
np.array(1)

# 1 D array -> vector which is similar to the list data structure from vanilla python
np.array([1,2,3,4])

# 2 D array -> matrix, which is like a list of lists
my_array =  np.array([[1,2,3], [4,5,6]])

In [ ]:
print(my_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
nrow, ncol = my_array.shape ## returns the shape of my_array by row, and then column
print(nrow)

2


#### Indexing
- indexing is done in a similar fashion to Python; however, if you have an ndim array where ndim > 1, then you have to multi-index

In [ ]:
# [row, column]
# let's say we have some matrix
# [[1 2 3]
#  [4 5 6]]
# and we want to get access to number 6,
# number 6, is in the 2nd row and the third column

my_array[1, 2]

6

#### Matplot
- matplotlib helps us plot and visualize our data using graphs, histograms, bar charts, curves, etc...

In [ ]:
## import matplot


In [ ]:
## x = [0,1,2,3,4]
## y = [0,1,2,3,4]

## let's plot y vs x








#### Plotting a sampled normal distribution
- Normal distribution is a bell curve that is symmetrical about the mean, at infinity, it approaches zero
- Standard normal curve has a mean of 0, and a standard deviation of 1

In [ ]:
import matplotlib.pyplot as plt
## let's make use of the np.random.normal function







#### Plotting Functions
- We can also plot functions using matplotlib instead of just plotting data points

In [ ]:
## let's use the np.linspace() function to generate x points and plot the sine graph








#### Plotting Time Series Data using yfinance
- So far, we've been plotting functions and sampling from distributions, but what if we want to plot real data?
- We can use the yfinance library to get stock data from Yahoo Finance and then plot it using matplotlib

In [ ]:
import yfinance as yf

In [ ]:
## let's plot the YTD (year to date 2024-01-01 to today) at a daily frequency for AAPL
## Tickers
## Microsoft -> MSFT
## TESLA -> TSLA







#### Comparing the performance of the magnificent 7
- Magnificent 7: Apple, Amazon, Google, Meta, Microsoft, Netflix, Tesla

In [ ]:
## in which stock did 100$ grow the most
## let's assume these stocks can be bought in non-integer amounts i.e. owning 0.33 shares of TSLA is allowed
## so, let's say hypothetically, i invested 100 dollars into each one of the following stocks:
## which one performed the best?
my_mag_7 = ['AAPL', 'AMZN', 'GOOG', 'META', 'MSFT', 'NFLX', 'TSLA']






